SboxAnalysis/Controllers/SboxController.cs
using ExcelDataReader;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using LinqToExcel;
using Microsoft.Office.Interop.Excel;
using SboxAnalysis.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SboxAnalysis.Controllers
{
    public class SboxController : Controller
    {
        // GET: Sbox
        public ActionResult Index()
        {
            ViewBag.Sbox = null;
            return View();
        }
        public JsonResult ImportSboxValues(string sboxStingValue)
        {
            var str = ImportSbox(sboxStingValue);
            return Json(str, JsonRequestBehavior.AllowGet);
        }

        private string ImportSbox(string sboxVal)
        {
            int[] sboxArr = new int[256];

            string[] sboxValues = new string[256];
            sboxValues = sboxVal.Split(',');
            var loop = 0;
            for (int i = 0; i < sboxValues.Length; i++)
            {
                sboxArr[loop] = Convert.ToByte(sboxValues[i]);
                loop++;
            }

            var str = GetHexValues(sboxArr);
            return str;
        }
        private string GetHexValues(int[] sboxArr)
        {
            byte[] sboxByteArr = new byte[256];
            var count = 0;
            for (int i = 0; i < sboxArr.Length; i++)
            {
                sboxByteArr[count] = Convert.ToByte(sboxArr[i]);

                count++;
            }
            string str = BitConverter.ToString(sboxByteArr);
            return str;
        }
        public JsonResult RandomSboxValues()
        {
            Random rnd = new Random();

            int[] sboxArr = new int[256];

            int uretilen = 255;
            while (uretilen > 0)
            {
                var rastgele = rnd.Next(0, 256);

                if (!sboxArr.Contains(rastgele))
                {
                    sboxArr[uretilen] = rastgele;
                    uretilen--;
                }
            }

            var rastgeleArr = rnd.Next(0, 256);
            var gecici = sboxArr[rastgeleArr];
            sboxArr[rastgeleArr] = sboxArr[0];
            sboxArr[0] = gecici;

            var str = GetHexValues(sboxArr);

            return Json(str, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ExportSboxValues(string sbox)
        {
            var sboxStrArr = new string[256];
            var sboxVal = "";

            sboxStrArr = sbox.Split('-');
            for (int i = 0; i < sboxStrArr.Length; i++)
            {
                sboxVal += int.Parse(sboxStrArr[i], System.Globalization.NumberStyles.HexNumber).ToString() + ',';
            }


            return Json(sboxVal, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Analysis(string sbox)
        {
            var sboxStrArr = new string[256];
            var sboxArr = new byte[256];

            sboxStrArr = sbox.Split('-');
            for (int i = 0; i < sboxStrArr.Length; i++)
            {
                sboxArr[i] = Convert.ToByte(int.Parse(sboxStrArr[i], System.Globalization.NumberStyles.HexNumber));
            }

            var result = CalculateLineerProbability(sboxArr);
            var s = ComparisonMatris(sboxStrArr);


            return Json(result, JsonRequestBehavior.AllowGet);
        }
        private LinearResultModel CalculateLineerProbability(byte[] sboxArr)
        {


            var linearResult = new LinearResultModel();
            var maxLinearVal = 0;
            var maxDifVal = 0;
            var lineerBiasArr = new int[256];
            var difBiasArr = new int[256];

            ///------------------------------------
            ///Lineer Hesaplamalar
            for (int j = 255; j > 0; j--)
            {
                for (int k = 255; k > 0; k--)
                {
                    var linearBias = 128;
                    var diffBias = 0;
                    for (int i = 255; i > 0; i--)
                    {
                        var byteNum = Convert.ToByte(i & j ^ sboxArr[i] & k);
                        linearBias -= Parity(byteNum);
                        diffBias += Convert.ToByte((sboxArr[i] ^ sboxArr[i ^ j]) == k);
                    }
                    if (Math.Abs(linearBias) > Math.Abs(maxLinearVal))
                    {
                        maxLinearVal = Math.Abs(linearBias);
                        //lineer işlemlerdeki değerlerin tümünü lineerBiasArr dizisine atar. 
                        //Dizide bulunan en küçük değer MaxLineer değeri olmakta. 
                        //En büyük değeri minLineer değeri olarak kullanılmakta(Doğruluğu şüpheli) 
                        lineerBiasArr[k] = Math.Abs(linearBias);
                    }
                    //Max dif hesaplama
                    if (diffBias > maxDifVal)
                    {
                        maxDifVal = diffBias;
                        difBiasArr[k] = diffBias;
                    }
                }
            }


            var difMin = difBiasArr.ToList().Where(x => x > 0).Min();
            var difMax = difBiasArr.ToList().Where(x => x > 0).Max();

            var linMin = lineerBiasArr.ToList().Where(x => x != 0).Min();
            var linMax = lineerBiasArr.ToList().Where(x => x != 0).Max();

            //var avgLin = lineerBiasArr.ToList().Where(x => x != 0).Average();
            double avgLin = ((linMax + linMin) / 2);
            var avgDif = difBiasArr.ToList().Where(x => x != 0).Average();

            linearResult.AvgLinearProbability = Math.Abs(Math.Round((avgLin / 2.56 / 100), 4));
            linearResult.MaxLinearProbability = Math.Abs(Math.Round((linMax / 2.56 / 100), 4));
            linearResult.MinLinearProbability = Math.Abs(Math.Round((linMin / 2.56 / 100), 4));

            linearResult.MaxDifferentialProbability = Math.Abs(Math.Round((difMax / 2.56 / 100), 4));
            linearResult.MinDifferentialProbability = Math.Abs(Math.Round((difMin / 2.56 / 100), 4));
            linearResult.AvgDifferentialProbability = Math.Abs(Math.Round((avgDif / 2.56 / 100), 4));

            var minNonLin = NonLinearity(linMax / 2, 8);
            var maxNonLin = NonLinearity(linMin / 2, 8);
            var avgNonLin = NonLinearity(Convert.ToInt32(avgLin / 2), 8);

            var nonLinMaxVal = 128 - linMax;
            var nonLinMinVal = 128 - linMin;
            var nonLinAvgVal = 128 - avgLin;

            linearResult.NonLinearProbabilityMax = nonLinMinVal;
            linearResult.NonLinearProbabilityMin = nonLinMaxVal;
            linearResult.NonLinearProbabilityAvg = Math.Round(nonLinAvgVal, 2);


            //avg ondalıklı geldiği için hata vermekte. Bu konu için nasıl ilerlenmeli ? int çevirmek doğru olur mu ?
            //var avgNonLin = NonLinearity(avgLin, 8);

            linearResult.MaxNonLinearProbability = Math.Abs(Math.Round(maxNonLin, 4));
            linearResult.MinNonLinearProbability = Math.Abs(Math.Round(minNonLin, 4));
            linearResult.AvgNonLinearProbability = Math.Abs(Math.Round(avgNonLin, 4));

            //Sac işlemleri
            var sac = sbox_sac_matrix(sboxArr, 3, 3);

            float totalSac = 0;
            var sacArr = new float[3];
            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {

                    totalSac += sac[i][j];
                }
                sacArr[i] = totalSac;
                totalSac = 0;
            }

            var sacAvg = sacArr.ToList().Sum() / 9;

            var sacMax = sacArr.ToList().Max();
            var sacMin = sacArr.ToList().Min();

            linearResult.SacAvg = Math.Round((sacAvg), 4);
            linearResult.SacMax = Math.Round((sacMax / 3), 4);
            linearResult.SacMin = Math.Round((sacMin / 3), 4);

            var bıc = sbox_bic(sboxArr, 3, 3);

            linearResult.BıcSacAvg = Math.Abs(Math.Round((bıc - sacAvg), 4));
            linearResult.BıcSacMin = Math.Abs(Math.Round((bıc - sacMin), 4));
            linearResult.BıcSacMax = Math.Abs(Math.Round((bıc - sacMax), 4));

            return linearResult;
        }

        public static byte Parity(byte sayi)
        {
            return Convert.ToByte(0x6996 >> ((sayi ^ sayi >> 4) & 15) & 1);
        }

        private double NonLinearity(int maxLin, int power)
        {
            var minNlp = 128 - maxLin;
            var n = Math.Pow(2, (power - 1));
            var n2 = Math.Pow(2, (power / 2 - 1));
            var minLinPer = Math.Abs(minNlp / (n - n2));
            return minLinPer;
        }

        private int two_power(int n)
        {
            var result = 1u << (n);

            return Convert.ToInt32(result);
        }

        private float[][] sbox_sac_matrix(byte[] sboxArr, int n, int m)
        {
            int i, j, X, ei, ej, dei;
            var sac = new float[3][];
            sac[0] = new float[3];
            sac[1] = new float[3];
            sac[2] = new float[3];

            for (i = 0; i < m; ++i)
            {
                ei = two_power(i);
                for (j = 0; j < n; ++j)
                {
                    ej = two_power(j);
                    for (X = 0; X < two_power(m); ++X)
                    {
                        dei = sboxArr[X] ^ sboxArr[X ^ ei];
                        sac[i][j] += (dei & ej) >> j; // increment sac[i][j] if bit at position j of dei is set
                    }
                }
            }

            float sacResult = 0;
            float outputLength = (float)two_power(n);
            for (i = 0; i < m; ++i)
            {
                for (j = 0; j < n; ++j)
                {
                    sac[i][j] /= outputLength;
                    sacResult += sac[i][j];
                }
            }

SboxAnalysis/Views/Sbox/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    #results {
        display: flex;
        flex-direction: column;
        align-items: stretch;
    }

    table {
        border-spacing: 0;
        border-collapse: collapse;
    }

    tr {
        padding: 0;
    }

    tbody tr:nth-child(odd) {
        background-color: #d9d9d9;
    }

    td {
        width: 40px;
        border: 1px solid #fe7914;
        text-align: center;
    }

    tbody td:first-child, thead td {
        background-color: #f0ad4e;
        color: #eee;
    }

        tbody tr:nth-child(odd) td:first-child, thead td:nth-child(even) {
            background-color: #fe7914;
        }
</style>

<div class="row" style="margin-top:5%">
    <div class="col-md-12">
        <div class="col-md-5">
            <button type="button" id="random" class="btn btn-primary">Random Generate</button>
            <button type="button" id="import" class="btn btn-success">Import</button>
            <button type="button" id="export" class="btn btn-warning">Export</button>
            <button type="button" id="analysis" class="btn btn-danger">Analysis</button>

        </div>
        <div class="col-md-2" style="margin-left:-9%">
            @using (Html.BeginForm("ExportHTML", "Sbox", FormMethod.Post))
            {
                <input type="hidden" name="ExportData" />
                <button type="submit" id="exportPdf" class="btn btn-danger">Export Pdf</button>

            }
        </div>
      
        <div class="col-md-4" style="margin-top:-16px;margin-left:-7%">
            @using (Html.BeginForm("Index", "Sbox", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return myFunction()" }))
            {
                <div class="form-group row">
                    <div class="col-md-3" style="margin-left: 63px; margin-top: -6%">
                        <input type="file" id="upload" name="upload" class="" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class=" col-md-3" style="">
                        <input type="submit" value="Upload Excel File" id="btnSubmit" class="btn" style="background-color:#efefef" />
                    </div>
                </div>

            }
        </div>
    </div>
</div>
<div class="row" style="margin-top:3%">
    <div class="col-md-12">
        <table>
            <thead>
                <tr>
                    <th>+</th>
                    <td>00</td>
                    <td>01</td>
                    <td>02</td>
                    <td>03</td>
                    <td>04</td>
                    <td>05</td>
                    <td>06</td>
                    <td>07</td>
                    <td>08</td>
                    <td>09</td>
                    <td>0A</td>
                    <td>0B</td>
                    <td>0C</td>
                    <td>0D</td>
                    <td>0E</td>
                    <td>0F</td>
                </tr>
            </thead>
            <tbody id="box" contenteditable>
            </tbody>
        </table>
    </div>
</div>
<div class="row" style="margin-top:5%">
    <div id="htmlSbox">
        <table class="table" style="width:100%; font-size:12px; border: 2px solid #ddd">
            <thead class="thead-dark" >
                <tr>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">Evalatuion</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">Linear Probability</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">Differancial Probability</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">Nonlinearty Percentage</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">Nonlinearty</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">SAC</th>
                    <th style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd" scope="col">BIC-SAC</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd">Maximum</td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"> <label class="control-label" id="linearMax"></label> </td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="difMax"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="nonLinMax"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="maxNonLin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="bıcSacMax"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="sacMax"></label></td>


                </tr>
                <tr style="border-left: 2px solid #ddd">
                    <td style="border-left: 2px solid #ddd; ">Minimum</td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="linearMin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="difMin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="nonLinMin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="minNonLin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="bıcSacMin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="sacMin"></label></td>


                </tr>
                <tr style="border-left: 2px solid #ddd">
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd">Avarage</td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"> <label class="control-label" id="linearAvg"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="difAvg"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="nonLinAvg"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="avgNonLin"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="bıcSacAvg"></label></td>
                    <td style="border-left: 2px solid #ddd; border-bottom: 2px solid #ddd"><label class="control-label" id="sacAvg"></label></td>

                </tr>
            </tbody>
        </table>
    </div>
</div>

<center><a href="/Home/Index" class="btn btn-success" style="width: 10%;border-radius: 1rem;border: none;">Home</a></center>

<input type="hidden" name="GridHtml" id="htmlValue" />
<input value="@ViewBag.Sbox" id="importSboxVal" type="hidden" />
<div class="row" style="margin-top:3%">
    <div class="col-md-8">
        <label id="sboxVal" class="label"></label>
    </div>

</div>
<script> 

    let SBOX = new Uint8Array(256);
    $(document).ready(function () {
        for (let i = 0; i < 16; ++i) {
            const tr = document.createElement('tr'),
                td = document.createElement('td');
            td.textContent = i.toString(16).toUpperCase() + '0';
            tr.appendChild(td);
            for (let j = 16; j--;)
                tr.appendChild(document.createElement('td'));
            box.appendChild(tr);
        }
        if ($("#importSboxVal").val() != null) {
            var data = $("#importSboxVal").val();
            loadGrid(data);
            SBOX = data;
        }


    });
    


    function loadGrid(data) {
        var arr = data.split('-');
        for (let i = 256; i--;)
            box.children[i >> 4].children[(i & 15) + 1].textContent = arr[i].toString(16).toUpperCase().padStart(2, '0');
    }

    $("#import").click(function () {
        const str = prompt('Enter the Sbox as comma separated values.');
        var sbox = new Object();
        sbox.sboxStingValue = str;
        if (str != null) {

            $.ajax({
                type: "POST",
                url: "/Sbox/ImportSboxValues",
                data: JSON.stringify(sbox),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: successFunc,
                error: errorFunc
            });

            function successFunc(data, status) {
                SBOX = data;
                loadGrid(data);
            }

            function errorFunc() {
                alert('error');
            }
        }
        else {

        }

    });


    $("#random").click(function () {

        $.ajax({
            type: "POST",
            url: "/Sbox/RandomSboxValues",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: successFunc,
            error: errorFunc
        });
        function successFunc(data, status) {
            SBOX = data;
            loadGrid(data);
        }

        function errorFunc() {
            alert('error');
        }
    });

    $("#analysis").click(function () {
        if (SBOX.byteOffset == 0) {
            alert("Please Enter Sbox Values");
        }
        else {
            var sbox = new Object();
            sbox.sbox = SBOX;

            $.ajax({
                type: "POST",
                url: "/Sbox/Analysis",
                data: JSON.stringify(sbox),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: successFunc,
                error: errorFunc
            });
            function successFunc(data, status) {
                $("#linearMax").text(data.MaxLinearProbability + '%');
                $("#linearMin").text(data.MinLinearProbability + '%');
                $("#linearAvg").text(data.AvgLinearProbability + '%');

                $("#difMax").text(data.MaxDifferentialProbability + '%');
                $("#difMin").text(data.MinDifferentialProbability + '%');
                $("#difAvg").text(data.AvgDifferentialProbability + '%');

                $("#nonLinMax").text(data.MaxNonLinearProbability + '%');
                $("#nonLinMin").text(data.MinNonLinearProbability + '%');
                $("#nonLinAvg").text(data.AvgNonLinearProbability + '%');

                $("#bıcSacAvg").text(data.BıcSacAvg + '%');
                $("#bıcSacMin").text(data.BıcSacMin + '%');
                $("#bıcSacMax").text(data.BıcSacMax + '%');

                $("#sacAvg").text(data.SacAvg + '%');
                $("#sacMin").text(data.SacMin + '%');
                $("#sacMax").text(data.SacMax + '%');
                $("#maxNonLin").text(data.NonLinearProbabilityMax);
                $("#minNonLin").text(data.NonLinearProbabilityMin);
                $("#avgNonLin").text(data.NonLinearProbabilityAvg);



                $("input[name='ExportData']").val($("#htmlSbox").html());


            }

            function errorFunc() {
                alert('error');
            }
        }

    });

    $("#export").click(function () {
        var sbox = new Object();
        sbox.sbox = SBOX;
        $.ajax({
            type: "POST",
            url: "/Sbox/ExportSboxValues",
            data: JSON.stringify(sbox),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: successFunc,
            error: errorFunc
        });
        function successFunc(data, status) {
            prompt('Ctrl + C to copy the Sbox', data)
        }

        function errorFunc() {
            alert('error');
        }
    });
</script>